services:
  fahrni:
    build:
      context: ../kirby
      dockerfile: Dockerfile
    image: kirby-apache:latest
    restart: unless-stopped
    volumes:
      - .:/var/www/site
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
      - fahrni-internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fahrni.rule=Host(`www.fahrni.ch`)"
      - "traefik.http.routers.fahrni.entrypoints=websecure"
      - "traefik.http.routers.fahrni.tls.certresolver=letsencrypt"
      - "traefik.http.services.fahrni.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
  fahrni-internal:
    internal: true
